$script = <<-SCRIPT
  sudo apt-get update

  sudo apt-get -y install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg \
      lsb-release
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  sudo apt-get update

  sudo apt-get -y install docker-ce docker-ce-cli containerd.io

  sudo usermod -aG docker vagrant

  docker run --name some-nginx -it -d -p 8080:80 nginx

  mkdir /home/vagrant/datadir
  sudo chown vagrant:vagrant /home/vagrant/datadir
  sudo chmod 775 /home/vagrant/datadir

  docker run --name some-mysql -v /home/vagrant/datadir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest

  # docker exec -i some-mysql mysql -u root -pmy-secret-pw <<< "CREATE USER 'userdb1' IDENTIFIED BY 'userdb1pass';"
  # docker exec -i some-mysql mysql -u root -pmy-secret-pw <<< "CREATE DATABASE costumdb;"  
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "shell", inline: $script
end

